{'edges': [{'id': 0, 'source': 'xQyve-kAAAAJ', 'target': '4-CJclQAAAAJ'},
           {'id': 36, 'source': 'xQyve-kAAAAJ', 'target': 'aZ6Cuh0AAAAJ'},
           {'id': 72, 'source': 'pagYxiQAAAAJ', 'target': 'jCcimzUAAAAJ'},
           {'id': 108, 'source': 'pagYxiQAAAAJ', 'target': 'Se4szUAAAAAJ'},
           {'id': 144, 'source': 'ya3htIoAAAAJ', 'target': '5n9E1cMAAAAJ'},
           {'id': 180, 'source': 'ya3htIoAAAAJ', 'target': 'q5vgzKgAAAAJ'},
           {'id': 216, 'source': 'ya3htIoAAAAJ', 'target': 'Pn0T4rQAAAAJ'},
           {'id': 252, 'source': 'ya3htIoAAAAJ', 'target': 'NibAlbMAAAAJ'},
           {'id': 288, 'source': 'ya3htIoAAAAJ', 'target': 'jUg1yFcAAAAJ'},
           {'id': 324, 'source': 'ya3htIoAAAAJ', 'target': 'saLJmksAAAAJ'},
           {'id': 360, 'source': 'ya3htIoAAAAJ', 'target': '4pWyfIQAAAAJ'},
           {'id': 396, 'source': 'ya3htIoAAAAJ', 'target': 'GOOxD60AAAAJ'},
           {'id': 432, 'source': '4-CJclQAAAAJ', 'target': 'ul-dSQQAAAAJ'},
           {'id': 468, 'source': '4-CJclQAAAAJ', 'target': 'iyEhyh4AAAAJ'},
           {'id': 504, 'source': '4-CJclQAAAAJ', 'target': 'fEAdMGAAAAAJ'},
           {'id': 540, 'source': '4-CJclQAAAAJ', 'target': 'giSjEBMAAAAJ'},
           {'id': 576, 'source': '4-CJclQAAAAJ', 'target': 'FXsV-ikAAAAJ'},
           {'id': 612, 'source': '4-CJclQAAAAJ', 'target': 'jUg1yFcAAAAJ'},
           {'id': 648, 'source': 'jUg1yFcAAAAJ', 'target': 'ul-dSQQAAAAJ'},
           {'id': 684, 'source': 'jUg1yFcAAAAJ', 'target': 'FXsV-ikAAAAJ'},
           {'id': 756, 'source': 'jUg1yFcAAAAJ', 'target': 'Pn0T4rQAAAAJ'},
           {'id': 792, 'source': 'jUg1yFcAAAAJ', 'target': 'saLJmksAAAAJ'},
           {'id': 828, 'source': 'jUg1yFcAAAAJ', 'target': '4pWyfIQAAAAJ'},
           {'id': 864, 'source': 'iyEhyh4AAAAJ', 'target': 'ul-dSQQAAAAJ'},
           {'id': 900, 'source': 'iyEhyh4AAAAJ', 'target': 'fEAdMGAAAAAJ'},
           {'id': 972, 'source': 'iyEhyh4AAAAJ', 'target': 'giSjEBMAAAAJ'},
           {'id': 1008, 'source': 'iyEhyh4AAAAJ', 'target': 'FXsV-ikAAAAJ'},
           {'id': 1044, 'source': 'iyEhyh4AAAAJ', 'target': 'jUg1yFcAAAAJ'},
           {'id': 1080, 'source': 'Oj0F9AkAAAAJ', 'target': 'aZ6Cuh0AAAAJ'},
           {'id': 1152, 'source': 'aZ6Cuh0AAAAJ', 'target': 'jUg1yFcAAAAJ'},
           {'id': 1224, 'source': 'aZ6Cuh0AAAAJ', 'target': 'MAylmIEAAAAJ'},
           {'id': 1260, 'source': '4pWyfIQAAAAJ', 'target': '5n9E1cMAAAAJ'},
           {'id': 1296, 'source': '4pWyfIQAAAAJ', 'target': 'NibAlbMAAAAJ'},
           {'id': 1404, 'source': '4pWyfIQAAAAJ', 'target': 'iMMncw8AAAAJ'},
           {'id': 1440, 'source': '4pWyfIQAAAAJ', 'target': 'Pn0T4rQAAAAJ'},
           {'id': 1476, 'source': '4pWyfIQAAAAJ', 'target': 'q5vgzKgAAAAJ'},
           {'id': 1512, 'source': 'giSjEBMAAAAJ', 'target': 'ul-dSQQAAAAJ'},
           {'id': 1548, 'source': 'giSjEBMAAAAJ', 'target': 'PwYT6EMAAAAJ'},
           {'id': 1584, 'source': 'giSjEBMAAAAJ', 'target': 'fEAdMGAAAAAJ'},
           {'id': 1620, 'source': 'giSjEBMAAAAJ', 'target': 'OTeSCfEAAAAJ'},
           {'id': 1728, 'source': 'giSjEBMAAAAJ', 'target': 'FXsV-ikAAAAJ'},
           {'id': 1764, 'source': 'giSjEBMAAAAJ', 'target': 'jUg1yFcAAAAJ'},
           {'id': 1836, 'source': '5n9E1cMAAAAJ', 'target': 'q5vgzKgAAAAJ'},
           {'id': 1872, 'source': '5n9E1cMAAAAJ', 'target': 'Pn0T4rQAAAAJ'},
           {'id': 1944, 'source': 'PwYT6EMAAAAJ', 'target': 'ul-dSQQAAAAJ'},
           {'id': 1980, 'source': 'PwYT6EMAAAAJ', 'target': 'sKzmsq8AAAAJ'},
           {'id': 2016, 'source': 'PwYT6EMAAAAJ', 'target': 'OTeSCfEAAAAJ'},
           {'id': 2196, 'source': 'Pn0T4rQAAAAJ', 'target': 'NibAlbMAAAAJ'},
           {'id': 2304, 'source': 'ul-dSQQAAAAJ', 'target': 'fEAdMGAAAAAJ'},
           {'id': 2412, 'source': 'ul-dSQQAAAAJ', 'target': 'FXsV-ikAAAAJ'},
           {'id': 2448, 'source': 'ul-dSQQAAAAJ', 'target': 'OTeSCfEAAAAJ'},
           {'id': 2520, 'source': 'ul-dSQQAAAAJ', 'target': 'sKzmsq8AAAAJ'},
           {'id': 2700, 'source': 'FXsV-ikAAAAJ', 'target': 'fEAdMGAAAAAJ'},
           {'id': 2916, 'source': 'sKzmsq8AAAAJ', 'target': 'OTeSCfEAAAAJ'},
           {'id': 2952, 'source': 'FtE4rAEAAAAJ', 'target': 'Iem4ceQAAAAJ'},
           {'id': 3060, 'source': 'q5vgzKgAAAAJ', 'target': 'saLJmksAAAAJ'},
           {'id': 3132, 'source': 'GOOxD60AAAAJ', 'target': 'qk4OUXEAAAAJ'},
           {'id': 3168, 'source': 'iMMncw8AAAAJ', 'target': 'saLJmksAAAAJ'}],
 'nodes': [{'affiliation': 'TU Delft',
            'citedby': 325,
            'citedby5y': 303,
            'coauthors': ['ul-dSQQAAAAJ',
                          'DmDWmy4AAAAJ',
                          'FXsV-ikAAAAJ',
                          'ya3htIoAAAAJ',
                          'Pn0T4rQAAAAJ',
                          'yewx0GgAAAAJ',
                          'saLJmksAAAAJ',
                          '4pWyfIQAAAAJ',
                          'jvlJKLkAAAAJ'],
            'email_domain': '@ulb.be',
            'interests': ['software engineering',
                          'robotics',
                          'swarm robotics',
                          'multi-robot systems',
                          'formal methods'],
            'name': 'Darko Bozhinoski',
            'organization': 0,
            'scholar_id': 'jUg1yFcAAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=jUg1yFcAAAAJ&citpid=1'},
           {'affiliation': 'PostDoctoral Researcher at TU Delft',
            'citedby': 928,
            'citedby5y': 747,
            'coauthors': ['Pkiw4DsAAAAJ',
                          '8CUEOlAAAAAJ',
                          'rH1CtQgAAAAJ',
                          'C01mErgAAAAJ',
                          '14dvkK4AAAAJ',
                          'DU4FPF0AAAAJ',
                          'e6lXMCQAAAAJ',
                          '4-CJclQAAAAJ',
                          'ZHZczW8AAAAJ',
                          'W2sWNiUAAAAJ',
                          'Egva5yQAAAAJ',
                          'aZ6Cuh0AAAAJ',
                          'TJRlyFQAAAAJ',
                          'DUv_tlYAAAAJ',
                          '9Xa9AwMAAAAJ'],
            'email_domain': '@upm.es',
            'interests': ['Decision Making',
                          'Navigation',
                          'Autonomous Vehicles'],
            'name': 'Mario Garzón Oviedo',
            'organization': 0,
            'scholar_id': 'xQyve-kAAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=xQyve-kAAAAJ&citpid=3'},
           {'affiliation': 'Norwegian School of Economics/Norges '
                           'Handelshøyskole',
            'citedby': 2891,
            'citedby5y': 2691,
            'coauthors': ['aAggyGwAAAAJ',
                          'uvZohTMAAAAJ',
                          '4SpTe5gAAAAJ',
                          'xyMRB8cAAAAJ',
                          '5NrehNoAAAAJ',
                          '8udO65kAAAAJ',
                          'N91wdCIAAAAJ',
                          'jd6Fbj8AAAAJ',
                          'ztt_j28AAAAJ',
                          'jCcimzUAAAAJ',
                          'XF56SOcAAAAJ',
                          'iUOaO58AAAAJ',
                          '3v4eOUgAAAAJ',
                          'Wy7ZZTEAAAAJ',
                          'x_7xA0UAAAAJ',
                          '04ndMy4AAAAJ',
                          'Cotye0kAAAAJ',
                          'L_HG640AAAAJ',
                          'Se4szUAAAAAJ',
                          'XyHMV6AAAAAJ',
                          'H0uqDCIAAAAJ'],
            'email_domain': '@nhh.no',
            'interests': ['Experimental Economics', 'Behavioral Economics'],
            'name': 'Siri Isaksson',
            'organization': 6484269306874944023,
            'scholar_id': 'pagYxiQAAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=pagYxiQAAAAJ&citpid=3'},
           {'affiliation': "King's College London; University of Toronto",
            'citedby': 7979,
            'citedby5y': 5327,
            'coauthors': [],
            'email_domain': '@kcl.ac.uk',
            'interests': ['mechanical ventilation',
                          'intensive care',
                          'home ventilation'],
            'name': 'Louise Rose',
            'organization': 1087198676816281164,
            'scholar_id': 'rca9ZrsAAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=rca9ZrsAAAAJ&citpid=1'},
           {'affiliation': 'Associate professor, S2 group, Vrije Universiteit '
                           'Amsterdam | Director of Network Institute',
            'citedby': 4361,
            'citedby5y': 3399,
            'coauthors': ['5n9E1cMAAAAJ',
                          'q5vgzKgAAAAJ',
                          'DmDWmy4AAAAJ',
                          'Pn0T4rQAAAAJ',
                          'NibAlbMAAAAJ',
                          'pvO-0xwAAAAJ',
                          'y8EX4DAAAAAJ',
                          '9LQwMlMAAAAJ',
                          'mdOf8ecAAAAJ',
                          'yhWELy4AAAAJ',
                          'h1CRic0AAAAJ',
                          'Az6jIMQAAAAJ',
                          'JVTAEMMAAAAJ',
                          'hH4XfiYAAAAJ',
                          'yewx0GgAAAAJ',
                          's8F7eWIAAAAJ',
                          'jUg1yFcAAAAJ',
                          'uwshWMoAAAAJ',
                          'cJ4inMcAAAAJ',
                          '_9E4gkoAAAAJ',
                          'BYsUAYoAAAAJ',
                          'hY2qbx0AAAAJ',
                          'x8XlRFgAAAAJ',
                          'saLJmksAAAAJ',
                          '92s7lqgAAAAJ',
                          'Tztbk7IAAAAJ',
                          'gwwHpGcAAAAJ',
                          'foPhI40AAAAJ',
                          'Gbh3VHQAAAAJ',
                          'ifF-jLQAAAAJ',
                          '9aI21r8AAAAJ',
                          'IDGSVEgAAAAJ',
                          'NsRgDcUAAAAJ',
                          '7F6-ubIAAAAJ',
                          'FcDxVR8AAAAJ',
                          'YJqcbnIAAAAJ',
                          's3RQeYQAAAAJ',
                          'Jv-sW70AAAAJ',
                          'hwcOgd4AAAAJ',
                          'PVIyHvUAAAAJ',
                          'jvlJKLkAAAAJ',
                          'kfxgNhUAAAAJ',
                          'shtLH2wAAAAJ',
                          'pazJN8cAAAAJ',
                          'l7BGAq8AAAAJ',
                          'mCLnJ94AAAAJ',
                          '6ImtercAAAAJ',
                          'w5wtyMEAAAAJ',
                          'j6ucyOAAAAAJ',
                          'ssqdGjUAAAAJ',
                          'bzxh-TsAAAAJ',
                          'gXtk7Y0AAAAJ',
                          '3s4lqHkAAAAJ',
                          'J4UGx-kAAAAJ',
                          'u74gQEUAAAAJ',
                          '5BK3-yYAAAAJ',
                          '4pWyfIQAAAAJ',
                          '_GJqkOEAAAAJ',
                          '3VYDPFgAAAAJ',
                          'ZmbkZVcAAAAJ',
                          '7JEh3MgAAAAJ',
                          '0yJmiKIAAAAJ',
                          'VaWnhK4AAAAJ',
                          'ZrPVvi8AAAAJ',
                          'aoOPOWAAAAAJ',
                          'eh9yS-QAAAAJ',
                          'Bz3TftwAAAAJ',
                          'Y9IZTE0AAAAJ',
                          'xT1X6coAAAAJ',
                          'yx0wJlIAAAAJ',
                          'xvzzSFgAAAAJ',
                          'p-rQXOQAAAAJ',
                          'iQlrBWkAAAAJ',
                          'gm6GQ5UAAAAJ',
                          'EqaYsE4AAAAJ',
                          'CI9BBSUAAAAJ',
                          'dr1Ymp8AAAAJ',
                          '5GH34v0AAAAJ',
                          '5EBfu-0AAAAJ',
                          'iGAkiI8AAAAJ',
                          'NMuDAe0AAAAJ',
                          'IXswbY8AAAAJ',
                          'dOeggYMAAAAJ',
                          'cMs97_YAAAAJ',
                          'bWBN3cwAAAAJ',
                          'QVzuSyIAAAAJ',
                          'DWJ2SS8AAAAJ',
                          '6Ld7HnYAAAAJ',
                          '30qXvJMAAAAJ',
                          'aps7_0IAAAAJ',
                          'EjWTDpoAAAAJ',
                          'IbxuCr4AAAAJ',
                          'Wr6oSWIAAAAJ',
                          'q7GJr9cAAAAJ',
                          'E_0SxewAAAAJ',
                          'Pban-xsAAAAJ',
                          'po_MgfcAAAAJ',
                          'sdw3WKQAAAAJ',
                          'kOMk-s4AAAAJ',
                          'aRd1i6UAAAAJ',
                          'GOOxD60AAAAJ',
                          'KDWpQIwAAAAJ',
                          'JwJZDtAAAAAJ',
                          'glRf46S0yTIC',
                          'NlBmV2QAAAAJ',
                          'NUJQv_oAAAAJ',
                          '_s8-1uAAAAAJ',
                          'oqyq_gQAAAAJ',
                          'ibP8SE8AAAAJ',
                          'R0C06GYAAAAJ',
                          '-bTkyxoAAAAJ',
                          '8svXaMoAAAAJ',
                          'dqJwPfkAAAAJ'],
            'email_domain': '@vu.nl',
            'interests': ['Software engineering',
                          'Software architecture',
                          'Green Software',
                          'Model-Driven Engineering'],
            'name': 'Ivano Malavolta',
            'organization': 1331960595593680101,
            'scholar_id': 'ya3htIoAAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=ya3htIoAAAAJ&citpid=8'},
           {'affiliation': 'Universidad Politécnica de Madrid',
            'citedby': 28,
            'citedby5y': 28,
            'coauthors': [],
            'email_domain': '@upm.es',
            'interests': ['self-awareness',
                          'control',
                          'metacontrol',
                          'reconfiguration',
                          'adaptation'],
            'name': 'Esther Aguado',
            'organization': 0,
            'scholar_id': 'MAylmIEAAAAJ',
            'url_picture': ''},
           {'affiliation': 'Université Libre de Bruxelles',
            'citedby': 456,
            'citedby5y': 444,
            'coauthors': ['ul-dSQQAAAAJ',
                          'Pkiw4DsAAAAJ',
                          '8CUEOlAAAAAJ',
                          '8tnO6EoAAAAJ',
                          'iyEhyh4AAAAJ',
                          'rH1CtQgAAAAJ',
                          'fEAdMGAAAAAJ',
                          'giSjEBMAAAAJ',
                          'FXsV-ikAAAAJ',
                          'bV0gT8QAAAAJ',
                          '8ZQZ_QUAAAAJ',
                          '9y-qO9cAAAAJ',
                          'uuVfRzgAAAAJ',
                          'jUg1yFcAAAAJ',
                          'OrODXkAAAAAJ',
                          'RoAXDw0AAAAJ',
                          'C01mErgAAAAJ',
                          'W-Pu1_QAAAAJ',
                          'CJTBYYcAAAAJ',
                          'Q26VrS4AAAAJ',
                          'DU4FPF0AAAAJ',
                          'V0tPMb8AAAAJ',
                          'l26SH70AAAAJ',
                          '00UgpcIAAAAJ'],
            'email_domain': '@ulb.ac.be',
            'interests': ['Swarm Robotics', 'Automatic Design', 'ROS'],
            'name': 'David Garzón Ramos',
            'organization': 0,
            'scholar_id': '4-CJclQAAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=4-CJclQAAAAJ&citpid=7'},
           {'affiliation': 'University of Groningen, University Medical Center '
                           'Groningen, Center for Human Movement Sciences',
            'citedby': 18981,
            'citedby5y': 7312,
            'coauthors': ['nWkK6p0AAAAJ',
                          'dlR1JTkAAAAJ',
                          'TNbcbU8AAAAJ',
                          'X7MPF3MAAAAJ',
                          'iV3fWRoAAAAJ',
                          'ElRJhvYAAAAJ',
                          'wXHZ1HwAAAAJ',
                          'qyeY5kIAAAAJ',
                          'O_aw4KQAAAAJ',
                          '2z2277EAAAAJ',
                          'K5ZfjMsAAAAJ',
                          'wDz2OlEAAAAJ',
                          '8CVMmXcAAAAJ',
                          '2tsS2jQAAAAJ',
                          'x2A0wesAAAAJ',
                          'D_3D89EAAAAJ',
                          'FTwWNOoAAAAJ',
                          '81E_Vu0AAAAJ',
                          'jr2EF9UAAAAJ',
                          'EYU_2E0AAAAJ',
                          'QXxtVHEAAAAJ',
                          'Gf4QzU4AAAAJ',
                          'JhqpL5wAAAAJ',
                          'zv-4koMAAAAJ',
                          'FQgTxjAAAAAJ',
                          'gD43gZkAAAAJ',
                          'F61gmCMAAAAJ',
                          'vQdHiOMAAAAJ',
                          'vxf-QEAAAAAJ',
                          'L4KuDxIAAAAJ',
                          'XcPAwHEAAAAJ',
                          '0UHZgToAAAAJ',
                          'ze5gkMMAAAAJ',
                          'Zv3fUJwAAAAJ',
                          'Ub2E1XAAAAAJ',
                          'Y-n9pyQAAAAJ',
                          '1ZxTxP4AAAAJ',
                          'OiF61NQAAAAJ',
                          'IAcFzakAAAAJ',
                          'WtPVytkAAAAJ',
                          '_bvBoV4AAAAJ',
                          'Lyj_SwEAAAAJ',
                          'ZREbZmwAAAAJ',
                          'r7f2LAoAAAAJ',
                          'xmjd1osAAAAJ',
                          'hrBCJ5oAAAAJ',
                          'HpPWrAQAAAAJ',
                          'iPodA9IAAAAJ',
                          'Fj1dv5MAAAAJ',
                          'E6KoJ0AAAAAJ',
                          'u2j1cZYAAAAJ',
                          'bruDuxoAAAAJ',
                          '6qBI-vAAAAAJ',
                          'ieQsAaYAAAAJ',
                          'qwz2bQQAAAAJ',
                          'lSuyTjsAAAAJ',
                          '0wzzn60AAAAJ',
                          'BG9q1TUAAAAJ',
                          '5k3lWTkAAAAJ',
                          'LDRTxEUAAAAJ',
                          'cTirmjUAAAAJ'],
            'email_domain': '@umcg.nl',
            'interests': ['Human movement sciences in rehabilitation',
                          'adapted physical activity',
                          'wheeled paralympic sports',
                          'ergonomics of wheeled mobility'],
            'name': 'L.H.V. van der Woude',
            'organization': 0,
            'scholar_id': 'lV5JQ08AAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=lV5JQ08AAAAJ&citpid=2'},
           {'affiliation': 'IRIDIA, Université Libre de Bruxelles, Lecturer at '
                           'ECAM Brussels',
            'citedby': 232,
            'citedby5y': 231,
            'coauthors': ['ul-dSQQAAAAJ',
                          'fEAdMGAAAAAJ',
                          '4-CJclQAAAAJ',
                          'giSjEBMAAAAJ',
                          'bV0gT8QAAAAJ',
                          'FXsV-ikAAAAJ',
                          'jUg1yFcAAAAJ',
                          '8tnO6EoAAAAJ',
                          'aqUq0AoAAAAJ',
                          'OKSkNx4AAAAJ'],
            'email_domain': '@ulb.ac.be',
            'interests': ['swarm robotics',
                          'automatic design',
                          'artificial intelligence',
                          'evolutionary robotics',
                          'neuroevolution'],
            'name': 'Ken Hasselmann',
            'organization': 0,
            'scholar_id': 'iyEhyh4AAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=iyEhyh4AAAAJ&citpid=13'},
           {'affiliation': 'Professor of Systems Engineering, Universidad '
                           'Politecnica de Madrid',
            'citedby': 2249,
            'citedby5y': 712,
            'coauthors': ['aZ6Cuh0AAAAJ',
                          'q-hNsrAAAAAJ',
                          'COgNuIEAAAAJ',
                          'tET7SJ8AAAAJ',
                          'KsYfSCIAAAAJ',
                          '_YbgbpEAAAAJ',
                          'umvlteoAAAAJ',
                          'kkVbtzAAAAAJ',
                          'rDkgzJQAAAAJ',
                          'RiOF_coAAAAJ',
                          'cMr49BsAAAAJ',
                          'gLnCTgIAAAAJ',
                          '9hqlOxcAAAAJ',
                          'btM72xsAAAAJ',
                          'oMtHaoQAAAAJ',
                          'Yg7Q_LYAAAAJ',
                          'MDFAXc8AAAAJ',
                          'wnDNSTEAAAAJ',
                          'o2NTLyoAAAAJ',
                          'l2ycxmwAAAAJ',
                          'yK4c37UAAAAJ',
                          'FUSt_SQAAAAJ',
                          'ZS-RjQsAAAAJ',
                          'QRaok3sAAAAJ',
                          'H9xADK0AAAAJ',
                          'JvInxPIAAAAJ',
                          'Pda0iMYAAAAJ',
                          'Pkiw4DsAAAAJ',
                          'OZIadUUAAAAJ',
                          'kIlO3SoAAAAJ',
                          '0orN2FUAAAAJ'],
            'email_domain': '@upm.es',
            'interests': ['Control systems',
                          'artificial intelligence',
                          'cognitive science',
                          'robotics'],
            'name': 'Ricardo Sanz',
            'organization': 0,
            'scholar_id': 'Oj0F9AkAAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=Oj0F9AkAAAAJ&citpid=3'},
           {'affiliation': 'Assistant professor at TU Delft',
            'citedby': 876,
            'citedby5y': 583,
            'coauthors': ['Oj0F9AkAAAAJ',
                          'Q4e_hkIAAAAJ',
                          'q-hNsrAAAAAJ',
                          'zFWBaFEAAAAJ',
                          'ddu5MKwAAAAJ',
                          'KsYfSCIAAAAJ',
                          'kkVbtzAAAAAJ',
                          'rDkgzJQAAAAJ',
                          'tET7SJ8AAAAJ',
                          'RiOF_coAAAAJ',
                          'KNMc_NsAAAAJ',
                          'COgNuIEAAAAJ',
                          'gLnCTgIAAAAJ',
                          '9hqlOxcAAAAJ',
                          'LMKnHkgAAAAJ',
                          'NwbkoewAAAAJ',
                          'jUg1yFcAAAAJ',
                          'xQyve-kAAAAJ',
                          'MTnzz0cAAAAJ',
                          'PXAsai8AAAAJ',
                          'bbFhmvMAAAAJ',
                          'FZIow6EAAAAJ',
                          'GgpJrwMAAAAJ',
                          'LhIdZS8AAAAJ',
                          'bRsi4zoAAAAJ',
                          'DU4FPF0AAAAJ',
                          'MAylmIEAAAAJ',
                          'Cfuw1rIAAAAJ',
                          'ZKQRE7cAAAAJ',
                          'm55TH88AAAAJ',
                          'z5LOK_oAAAAJ',
                          'Qg47-BsAAAAJ',
                          '7Y7FSNAAAAAJ',
                          'FncBQzIAAAAJ',
                          'U8S86d4AAAAJ',
                          'trJR5IQAAAAJ',
                          '1yWt8GIAAAAJ'],
            'email_domain': '@tudelft.nl',
            'interests': ['autonomous robots',
                          'AI',
                          'self-adaptive systems',
                          'knowledge-representation and reasoning',
                          'model-based systems engineering'],
            'name': 'Carlos Hernández Corbato',
            'organization': 814705155794667179,
            'scholar_id': 'aZ6Cuh0AAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=aZ6Cuh0AAAAJ&citpid=1'},
           {'affiliation': 'FBK-MoDiS, Trento, Italy',
            'citedby': 3445,
            'citedby5y': 1586,
            'coauthors': ['_GJqkOEAAAAJ',
                          '82iNabUAAAAJ',
                          'vkhTk-MAAAAJ',
                          'DmDWmy4AAAAJ',
                          't_RaFkgAAAAJ',
                          'th6g2bgAAAAJ',
                          'VaWnhK4AAAAJ',
                          'I-9eMoMAAAAJ',
                          'M9hLHUkAAAAJ',
                          'WNefTDUAAAAJ',
                          '0n5S6uUAAAAJ',
                          '5n9E1cMAAAAJ',
                          '4aDHDyoAAAAJ',
                          '2xV8DfcAAAAJ',
                          '-Ihy2bkAAAAJ',
                          '0SzKXGwAAAAJ',
                          'JVTAEMMAAAAJ',
                          'vwfw0lwAAAAJ',
                          'LaGRXwkAAAAJ',
                          'bLFVsAQAAAAJ',
                          'dCpNZEAAAAAJ',
                          'cadDotQAAAAJ',
                          'pCgQvJgAAAAJ',
                          'df9bzkoAAAAJ',
                          'ho38I-wAAAAJ',
                          'Gn6eGyoAAAAJ',
                          'HzFjuyUAAAAJ',
                          '_6zceo4AAAAJ',
                          'WZAn2CwAAAAJ',
                          'L0NCDwsAAAAJ',
                          'M6Pn0vEAAAAJ',
                          'F76PiIIAAAAJ',
                          'jvlJKLkAAAAJ',
                          '9aotp4YAAAAJ',
                          'rS4GcY0AAAAJ',
                          '86H7HmkAAAAJ',
                          'OKLqWgMAAAAJ',
                          'TFLSep0AAAAJ',
                          'OeYEcWkAAAAJ',
                          'NibAlbMAAAAJ',
                          'vQkGBJIAAAAJ',
                          'JsrZG2YAAAAJ',
                          'nLOPh-oAAAAJ',
                          'pvrJk-8AAAAJ',
                          '_QlhB4kAAAAJ',
                          'LopGujQAAAAJ',
                          'onAoWhIAAAAJ',
                          'uXqL1-YAAAAJ',
                          '0CLlt5oAAAAJ',
                          'JdHlU2EAAAAJ',
                          'iM_zOn0AAAAJ',
                          'OaLN594AAAAJ',
                          'TIOqO4wAAAAJ',
                          'jUg1yFcAAAAJ',
                          'ya3htIoAAAAJ',
                          'EIQ6h-wAAAAJ',
                          '0SpTvsUAAAAJ',
                          'tbVxns0AAAAJ',
                          'KXfVZq0AAAAJ',
                          'zRA6uA4AAAAJ',
                          'fuknxZsAAAAJ',
                          'mHvJojUAAAAJ',
                          'nVbpWQoAAAAJ',
                          'zO9OcTMAAAAJ',
                          'igMJAZwAAAAJ',
                          'XifW61cAAAAJ',
                          'HoVTdWwAAAAJ',
                          '5-tRnxkAAAAJ',
                          'hnc9E2AAAAAJ',
                          'Ycwf7Z4AAAAJ',
                          '6ImtercAAAAJ',
                          'AbJrH_EAAAAJ',
                          'Cnste6IAAAAJ',
                          'lOFQGacAAAAJ',
                          'iMMncw8AAAAJ',
                          'xeL-QIoAAAAJ',
                          'Pn0T4rQAAAAJ',
                          'sKdlorMAAAAJ',
                          '_ZSyxZ8AAAAJ',
                          'P7Egf8wAAAAJ',
                          'gXtk7Y0AAAAJ',
                          '1h9WcVQAAAAJ',
                          'q5vgzKgAAAAJ',
                          'ePdu-uwAAAAJ',
                          '6iLf1_IAAAAJ',
                          '7_-VBTkAAAAJ',
                          '9tcp0OoAAAAJ',
                          'aIes6jIAAAAJ',
                          '5shVHyoAAAAJ',
                          'nQFCxmkAAAAJ',
                          'qhfWK44AAAAJ',
                          't8C0QmIAAAAJ',
                          'V8a2E-oAAAAJ',
                          'SI_uHCIAAAAJ',
                          'binoVEgAAAAJ',
                          'IfMKjBgAAAAJ',
                          'q7GJr9cAAAAJ',
                          'x8XlRFgAAAAJ',
                          'i5To0fcAAAAJ',
                          'gq9hIiAAAAAJ',
                          'F7yujycAAAAJ',
                          '4fCqGkwAAAAJ',
                          'J0KSGWEAAAAJ',
                          '1FIyc9kAAAAJ',
                          'BXNmr_AAAAAJ',
                          'Sq_ovbQAAAAJ',
                          'VKb7dksAAAAJ',
                          'LerCqoZzM9EC',
                          '6z5NNe4AAAAJ',
                          '0_onpPkAAAAJ',
                          'kAkElBUAAAAJ',
                          'P4nfoKYAAAAJ',
                          'D1eifv4AAAAJ',
                          'nvqR2P8AAAAJ',
                          'hyFIq8UAAAAJ',
                          'yyrCzBEAAAAJ',
                          'qRnegTsAAAAJ',
                          '_NqFoiYAAAAJ',
                          'd3NP0v8AAAAJ',
                          'tygGKvsAAAAJ',
                          'FxdRLcIAAAAJ'],
            'email_domain': '@fbk.eu',
            'interests': ['Self-Adaptation',
                          'Domain-Specific Languages',
                          'Gamification',
                          'Multi-Agent Systems',
                          'SOA'],
            'name': 'Antonio Bucchiarone',
            'organization': 8352841911256301593,
            'scholar_id': '4pWyfIQAAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=4pWyfIQAAAAJ&citpid=1'},
           {'affiliation': 'PhD candidate at TU Delft',
            'citedby': 28,
            'citedby5y': 27,
            'coauthors': ['4KPuGDYAAAAJ',
                          'XSC9o6wAAAAJ',
                          'Ma1iM1YAAAAJ',
                          'ES2-5NEAAAAJ',
                          '9uqxFe8AAAAJ'],
            'email_domain': '@tudelft.nl',
            'interests': ['robotics',
                          'artificial intelligence',
                          'agents',
                          'computer vision'],
            'name': 'Gustavo Rezende Silva',
            'organization': 814705155794667179,
            'scholar_id': 'CpkcBHYAAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=CpkcBHYAAAAJ&citpid=2'},
           {'affiliation': 'Toyota Motor Europe & IRIDIA CoDE, Université '
                           'Libre de Bruxelles',
            'citedby': 1225,
            'citedby5y': 998,
            'coauthors': ['ul-dSQQAAAAJ',
                          '8ZQZ_QUAAAAJ',
                          'h-oGBzsAAAAJ',
                          '21RkigUAAAAJ',
                          'rUSxe4AAAAAJ',
                          'V1s0tTwAAAAJ',
                          'ZDTF5AEAAAAJ',
                          'WTQ2f0QAAAAJ',
                          'aE8woBcAAAAJ',
                          '8CjJtbMAAAAJ',
                          'PwYT6EMAAAAJ',
                          'fEAdMGAAAAAJ',
                          'OTeSCfEAAAAJ',
                          '6hAfhicAAAAJ',
                          'iyEhyh4AAAAJ',
                          'OrODXkAAAAAJ',
                          'aTqbxmcAAAAJ',
                          'WOC8dIcAAAAJ',
                          '1CLaPMEAAAAJ',
                          '59DUkRYAAAAJ',
                          '8tnO6EoAAAAJ',
                          '4-CJclQAAAAJ',
                          'EZJovNQAAAAJ',
                          'FXsV-ikAAAAJ',
                          'uuVfRzgAAAAJ',
                          'jUg1yFcAAAAJ',
                          'RJl0GfwAAAAJ',
                          'jAdtRboAAAAJ',
                          'RoAXDw0AAAAJ',
                          'dWp-G3AAAAAJ',
                          'Mhs4vMMAAAAJ',
                          'ZXWGvnIAAAAJ',
                          'pzDPJecAAAAJ',
                          '00UgpcIAAAAJ',
                          'HdRZK14AAAAJ'],
            'email_domain': '@toyota-europe.com',
            'interests': ['computer vision',
                          'human monitoring',
                          'scene understanding',
                          'Swarm Robotics (for fun)'],
            'name': 'Gianpiero Francesca',
            'organization': 0,
            'scholar_id': 'giSjEBMAAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=giSjEBMAAAAJ&citpid=4'},
           {'affiliation': 'Full Professor in Computer Science, University of '
                           "L'Aquila",
            'citedby': 4742,
            'citedby5y': 2042,
            'coauthors': ['DmDWmy4AAAAJ',
                          'ya3htIoAAAAJ',
                          'x8XlRFgAAAAJ',
                          'mCLnJ94AAAAJ',
                          'q5vgzKgAAAAJ',
                          'i5To0fcAAAAJ',
                          'be0lMAoAAAAJ',
                          'Pn0T4rQAAAAJ',
                          'qtITyHkAAAAJ',
                          'h1CRic0AAAAJ',
                          'yhWELy4AAAAJ',
                          'vQkGBJIAAAAJ',
                          '4pWyfIQAAAAJ',
                          'JVTAEMMAAAAJ',
                          's4JPUOEAAAAJ',
                          'FWL9hEoAAAAJ',
                          'Tztbk7IAAAAJ',
                          'Gv9zHcEAAAAJ',
                          'gwwHpGcAAAAJ',
                          'MG8iJPAAAAAJ',
                          'vL6ubpMAAAAJ',
                          'P4vK_ZUAAAAJ',
                          'l7BGAq8AAAAJ',
                          'UipfbPAAAAAJ',
                          'yewx0GgAAAAJ',
                          '92s7lqgAAAAJ',
                          'nzIGpU4AAAAJ',
                          'J4UGx-kAAAAJ',
                          'nxQBSlgAAAAJ',
                          'LaGRXwkAAAAJ',
                          'pvrJk-8AAAAJ',
                          '4YAdfEsAAAAJ',
                          'is1bSSMAAAAJ',
                          'OptQ3jwAAAAJ',
                          'h3L7zkoAAAAJ',
                          'QVzuSyIAAAAJ',
                          'oagBheUAAAAJ',
                          'shtLH2wAAAAJ',
                          'V5ILAxAAAAAJ',
                          'mEASLGcAAAAJ',
                          'wEU99lsAAAAJ',
                          'k6b-lLYAAAAJ',
                          'yiijLskAAAAJ',
                          'IXswbY8AAAAJ',
                          'qGe7nJ0AAAAJ',
                          'gXtk7Y0AAAAJ',
                          'BseLkiIAAAAJ',
                          'aps7_0IAAAAJ',
                          'FyUQvCoAAAAJ',
                          'qkHucrkAAAAJ',
                          '-GbIBV8AAAAJ',
                          'j4QfXDgAAAAJ',
                          'gq9hIiAAAAAJ',
                          'ECn3RoMAAAAJ',
                          'w5wtyMEAAAAJ',
                          '4aDHDyoAAAAJ',
                          'pQfY6w4AAAAJ',
                          'FRKV5UcAAAAJ',
                          'uwshWMoAAAAJ',
                          '8svXaMoAAAAJ'],
            'email_domain': '@univaq.it',
            'interests': ['Software Architecture',
                          'Model Driven Engineering',
                          'Verification and Validation'],
            'name': 'Henry Muccini',
            'organization': 4242138795926591801,
            'scholar_id': '5n9E1cMAAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=5n9E1cMAAAAJ&citpid=6'},
           {'affiliation': 'FNRS Research Director, IRIDIA, Université Libre '
                           'de Bruxelles',
            'citedby': 137012,
            'citedby5y': 36239,
            'coauthors': ['ul-dSQQAAAAJ',
                          'OrODXkAAAAAJ',
                          'SCCwW3YAAAAJ',
                          'pSalOJAAAAAJ',
                          'bwzA5A0AAAAJ',
                          'WTQ2f0QAAAAJ',
                          'aE8woBcAAAAJ',
                          'cVjuZJoAAAAJ',
                          'HdRZK14AAAAJ',
                          'sKzmsq8AAAAJ',
                          'pX471uAAAAAJ',
                          'T_LzDF4AAAAJ',
                          's-Unqd8AAAAJ',
                          '21RkigUAAAAJ',
                          'piEqyCsAAAAJ',
                          'aCZ8taYAAAAJ',
                          'YVqJ_u8AAAAJ',
                          'mjueH64AAAAJ',
                          'u_BY4fAAAAAJ',
                          'pzDPJecAAAAJ',
                          '4e-ykx0AAAAJ',
                          'a5MoXOYAAAAJ',
                          'HUoutmwAAAAJ',
                          'kkSZGKoAAAAJ',
                          'sQTVDz8AAAAJ',
                          'qDZdA5EAAAAJ',
                          '9RyMwCQAAAAJ',
                          'ZXWGvnIAAAAJ',
                          'ZycQHdgAAAAJ',
                          'aO-849gAAAAJ',
                          'OTeSCfEAAAAJ',
                          'JOSA-HUAAAAJ',
                          'nltQkfgAAAAJ',
                          'cBb3cm0AAAAJ',
                          'RoAXDw0AAAAJ',
                          '6jNgTK4AAAAJ',
                          'q_47tpEAAAAJ',
                          'Ya3hxoEAAAAJ',
                          'WGsfZEEAAAAJ',
                          'vj-4SjYAAAAJ',
                          'UkbqBZ4AAAAJ',
                          'JP35tzwAAAAJ',
                          'zTalrDgAAAAJ',
                          'ytCUgJMAAAAJ',
                          '8RhRoxgAAAAJ',
                          'BUzKxsoAAAAJ',
                          '94iaPoUAAAAJ',
                          'jAdtRboAAAAJ',
                          'DJ7D-YwAAAAJ',
                          'giSjEBMAAAAJ',
                          'h9pOfj0AAAAJ',
                          '4MNHWX8AAAAJ',
                          'CrHB1LQAAAAJ',
                          'G0aB6eMAAAAJ',
                          '8w3vnUcAAAAJ',
                          'LkiweUgAAAAJ',
                          'RUfo3KoAAAAJ',
                          'yKNNv8kAAAAJ',
                          'dBqrIf0AAAAJ',
                          'rx56n5cAAAAJ',
                          'Uww3NcYAAAAJ',
                          'APNDyx0AAAAJ',
                          'Kp5fFpYAAAAJ',
                          'aZVYm64AAAAJ',
                          'WgHd_voAAAAJ',
                          'FU8ms0kAAAAJ',
                          'V4jpBB4AAAAJ',
                          'XZFOFSwAAAAJ',
                          'SoPbc_QAAAAJ',
                          'biRr-ycAAAAJ',
                          'AX3nkHsAAAAJ',
                          '8_eGIuEAAAAJ',
                          '00UgpcIAAAAJ',
                          '8EdHVuYAAAAJ',
                          '_YPEuOUAAAAJ'],
            'email_domain': '@ulb.ac.be',
            'interests': ['Swarm Intelligence',
                          'Swarm Robotics',
                          'Metaheuristics',
                          'Computational Intelligence'],
            'name': 'Marco Dorigo',
            'organization': 0,
            'scholar_id': 'PwYT6EMAAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=PwYT6EMAAAAJ&citpid=3'},
           {'affiliation': "Associate Professor, DISIM, University of L'Aquila "
                           '(Italy)',
            'citedby': 4778,
            'citedby5y': 2688,
            'coauthors': ['JVTAEMMAAAAJ',
                          'PNagLbIAAAAJ',
                          '9LQwMlMAAAAJ',
                          'DmDWmy4AAAAJ',
                          'vxFDCLUAAAAJ',
                          'I-9eMoMAAAAJ',
                          'aRd1i6UAAAAJ',
                          'ya3htIoAAAAJ',
                          'n7G7HfgAAAAJ',
                          's8F7eWIAAAAJ',
                          '5n9E1cMAAAAJ',
                          'R6_Uhtra2oUC',
                          'w5wtyMEAAAAJ',
                          'x8XlRFgAAAAJ',
                          'lZjytHUAAAAJ',
                          'jvlJKLkAAAAJ',
                          'HzFjuyUAAAAJ',
                          'mVLEIJQAAAAJ',
                          'mdOf8ecAAAAJ',
                          'yhWELy4AAAAJ',
                          'j6ucyOAAAAAJ',
                          '5-tRnxkAAAAJ',
                          'ThbSyVoAAAAJ',
                          'YZDY1psAAAAJ',
                          'jUg1yFcAAAAJ',
                          's4JPUOEAAAAJ',
                          'rlhpWRQAAAAJ',
                          'NibAlbMAAAAJ',
                          '7TpvePQAAAAJ',
                          'r9PtMIcAAAAJ',
                          'yewx0GgAAAAJ',
                          'RNXCw-4AAAAJ',
                          'Dvp7fNoAAAAJ',
                          '-nX4P3AAAAAJ',
                          's5-YWPQAAAAJ',
                          'mLC0j_UAAAAJ',
                          'eFELsf0AAAAJ',
                          'Johd4IEAAAAJ',
                          '-MUMAeAAAAAJ',
                          'g1SnTPUAAAAJ',
                          'wfT-AoEAAAAJ',
                          'hrwUrF8AAAAJ',
                          'BqfL80YAAAAJ',
                          'QVzuSyIAAAAJ',
                          'i5To0fcAAAAJ',
                          'gXtk7Y0AAAAJ',
                          'aZKRy1oAAAAJ',
                          'r1lCltMAAAAJ',
                          'q2_sZiMAAAAJ',
                          'QMZSalkAAAAJ',
                          '1h9WcVQAAAAJ',
                          '3Ug2MrwAAAAJ',
                          'wQ-JEO8AAAAJ',
                          'n8OstxEAAAAJ',
                          'gDL_aukAAAAJ',
                          'V6LSabIAAAAJ',
                          '5E-bnRkAAAAJ',
                          'yCwXGPQAAAAJ',
                          'Bz3TftwAAAAJ',
                          'CYfxRVIAAAAJ',
                          '5x8BvrsAAAAJ',
                          'nED1C7QAAAAJ',
                          'is1bSSMAAAAJ',
                          '3mjTIm0AAAAJ',
                          '4Ya6dVoAAAAJ',
                          'D2L9kWAAAAAJ'],
            'email_domain': '@di.univaq.it',
            'interests': ['Software Engineering',
                          'Model-Driven Engineering',
                          'Software Modeling',
                          'Domain-Specific Languages',
                          'Recommender Systems'],
            'name': 'Davide Di Ruscio',
            'organization': 4242138795926591801,
            'scholar_id': 'Pn0T4rQAAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=Pn0T4rQAAAAJ&citpid=5'},
           {'affiliation': 'F.R.S.–FNRS Research Director, IRIDIA, Université '
                           'libre de Bruxelles',
            'citedby': 31717,
            'citedby5y': 13137,
            'coauthors': ['PwYT6EMAAAAJ',
                          'OrODXkAAAAAJ',
                          'aE8woBcAAAAJ',
                          'SX-QoHsAAAAJ',
                          'cVjuZJoAAAAJ',
                          'ZycQHdgAAAAJ',
                          'giSjEBMAAAAJ',
                          'u_BY4fAAAAAJ',
                          'jAdtRboAAAAJ',
                          'fEAdMGAAAAAJ',
                          'q_47tpEAAAAJ',
                          '8ZQZ_QUAAAAJ',
                          'RoAXDw0AAAAJ',
                          'WTQ2f0QAAAAJ',
                          'iyEhyh4AAAAJ',
                          '4-CJclQAAAAJ',
                          'FXsV-ikAAAAJ',
                          'bwzA5A0AAAAJ',
                          '8tnO6EoAAAAJ',
                          'OTeSCfEAAAAJ',
                          'tQVYKucAAAAJ',
                          'jUg1yFcAAAAJ',
                          'sKzmsq8AAAAJ',
                          'EZJovNQAAAAJ',
                          'bV0gT8QAAAAJ',
                          '2Uu05X4AAAAJ',
                          'uuVfRzgAAAAJ',
                          'FU8ms0kAAAAJ',
                          'QlfCJrQAAAAJ',
                          'aO-849gAAAAJ',
                          '2A6PMfEAAAAJ',
                          'yD-SFG4AAAAJ',
                          'W-Pu1_QAAAAJ',
                          'HdRZK14AAAAJ',
                          '00UgpcIAAAAJ',
                          '8EdHVuYAAAAJ'],
            'email_domain': '@ulb.ac.be',
            'interests': ['swarm robotics',
                          'evolutionary robotics',
                          'swarm intelligence',
                          'automatic design'],
            'name': 'Mauro Birattari',
            'organization': 0,
            'scholar_id': 'ul-dSQQAAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=ul-dSQQAAAAJ&citpid=4'},
           {'affiliation': 'Associate Professor at Mälardalen University',
            'citedby': 1473,
            'citedby5y': 1127,
            'coauthors': ['I-9eMoMAAAAJ',
                          'K8v5JfgAAAAJ',
                          'sdw3WKQAAAAJ',
                          'gH5Au04AAAAJ',
                          'JVTAEMMAAAAJ',
                          'HN2jefgAAAAJ',
                          'yewx0GgAAAAJ',
                          'cpeuyfAAAAAJ',
                          'io3wqUoAAAAJ',
                          'F0NesSQAAAAJ',
                          'k2DE-wkAAAAJ',
                          '_NqFoiYAAAAJ',
                          'w5wtyMEAAAAJ',
                          'arxht7cAAAAJ',
                          '2xV8DfcAAAAJ',
                          '-PXi_dgAAAAJ',
                          'CTItQAQAAAAJ',
                          'EtLtHhIAAAAJ',
                          '-xwB1UoAAAAJ',
                          'qdvXc8kAAAAJ',
                          'gGLdjasAAAAJ',
                          '_XLRuYAAAAAJ',
                          'yYnpdyoAAAAJ',
                          '4Ya6dVoAAAAJ',
                          'MJ1d84oAAAAJ',
                          'k33GvKMAAAAJ',
                          'mxLMEuwAAAAJ',
                          'MOBlyEEAAAAJ'],
            'email_domain': '@mdu.se',
            'interests': ['Software Engineering',
                          'Model-Driven Engineering',
                          'Component-Based Software Engineering',
                          'Embedded Systems'],
            'name': 'Federico Ciccozzi',
            'organization': 0,
            'scholar_id': 'NibAlbMAAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=NibAlbMAAAAJ&citpid=5'},
           {'affiliation': 'FNRS Research Fellow in Collective Behaviour, '
                           'IRIDIA, Université Libre de Bruxelles, Belgium',
            'citedby': 1140,
            'citedby5y': 975,
            'coauthors': ['VNMIqx4AAAAJ',
                          'WTQ2f0QAAAAJ',
                          'PwYT6EMAAAAJ',
                          'jNnTvM0AAAAJ',
                          'ul-dSQQAAAAJ',
                          'aE8woBcAAAAJ',
                          'ME8ueC0AAAAJ',
                          'aTqbxmcAAAAJ',
                          'giSjEBMAAAAJ',
                          '8ZQZ_QUAAAAJ',
                          '6hAfhicAAAAJ',
                          'mjueH64AAAAJ',
                          'w_OQZmsAAAAJ',
                          'p6ciQG8AAAAJ',
                          'bwzA5A0AAAAJ',
                          'HUoutmwAAAAJ',
                          'Z8lBRZkAAAAJ',
                          's-Unqd8AAAAJ',
                          'Etp0VTgAAAAJ',
                          'cVjuZJoAAAAJ',
                          'zTalrDgAAAAJ',
                          'EjjwrswAAAAJ',
                          'pzDPJecAAAAJ',
                          'TpQ2niQAAAAJ'],
            'email_domain': '@ulb.be',
            'interests': ['Swarm Robotics',
                          'Collective Decision Making',
                          'Distributed Cognition'],
            'name': 'Andreagiovanni Reina',
            'organization': 0,
            'scholar_id': 'OTeSCfEAAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=OTeSCfEAAAAJ&citpid=2'},
           {'affiliation': 'Erasmus University Rotterdam',
            'citedby': 1413,
            'citedby5y': 1403,
            'coauthors': [],
            'email_domain': '@ese.eur.nl',
            'interests': ['Experimental Finance/Economics'],
            'name': 'Julia Rose',
            'organization': 0,
            'scholar_id': 'Se4szUAAAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=Se4szUAAAAAJ&citpid=4'},
           {'affiliation': "School of Computing, Queen's University, Canada",
            'citedby': 3619,
            'citedby5y': 1127,
            'coauthors': [],
            'email_domain': '@cs.queensu.ca',
            'interests': ['Software engineering',
                          'formal methods',
                          'software modeling',
                          'model-driven engineering',
                          'analysis of software artifacts'],
            'name': 'Juergen Dingel',
            'organization': 0,
            'scholar_id': 'MZggB6kAAAAJ',
            'url_picture': ''},
           {'affiliation': 'University of Konstanz',
            'citedby': 176,
            'citedby5y': 175,
            'coauthors': ['ul-dSQQAAAAJ',
                          'fEAdMGAAAAAJ',
                          'jUg1yFcAAAAJ',
                          '4-CJclQAAAAJ',
                          'iyEhyh4AAAAJ',
                          '8tnO6EoAAAAJ',
                          'OrODXkAAAAAJ',
                          'uuVfRzgAAAAJ',
                          'bV0gT8QAAAAJ',
                          'W-Pu1_QAAAAJ',
                          'l26SH70AAAAJ'],
            'email_domain': '@uni-konstanz.de',
            'interests': ['Swarm Robotics',
                          'Design by Optimization',
                          'Automatic Design',
                          'Artificial Intelligence'],
            'name': 'Jonas Kuckling',
            'organization': 0,
            'scholar_id': 'FXsV-ikAAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=FXsV-ikAAAAJ&citpid=4'},
           {'affiliation': 'Erasmus mc Rotterdam',
            'citedby': 22708,
            'citedby5y': 8312,
            'coauthors': [],
            'email_domain': '@erasmusmc.nl',
            'interests': ['rehabilitation'],
            'name': 'henk Stam',
            'organization': 0,
            'scholar_id': 'vXJ89Z4AAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=vXJ89Z4AAAAJ&citpid=1'},
           {'affiliation': 'Professor of Computer Science, Carnegie Mellon '
                           'University',
            'citedby': 41337,
            'citedby5y': 5855,
            'coauthors': [],
            'email_domain': '@cs.cmu.edu',
            'interests': ['software architecture',
                          'self-adaptive systems',
                          'end-user architecting'],
            'name': 'David Garlan',
            'organization': 0,
            'scholar_id': 'saLJmksAAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=saLJmksAAAAJ&citpid=1'},
           {'affiliation': 'SDU Biorobotics, MMMI, University of Southern '
                           'Denmark (SDU)',
            'citedby': 3849,
            'citedby5y': 1996,
            'coauthors': ['PwYT6EMAAAAJ',
                          '73G4jpkAAAAJ',
                          'cCiaIMwAAAAJ',
                          '_u9LaIEAAAAJ',
                          'ACFMnjMAAAAJ',
                          '2IbMjzgAAAAJ',
                          'JFJVgxQAAAAJ',
                          'r8zV1FsAAAAJ',
                          '4tVp8T4AAAAJ',
                          'fO21UBwAAAAJ',
                          's-Unqd8AAAAJ',
                          'sQTVDz8AAAAJ',
                          'R-Gyat8AAAAJ',
                          'ul-dSQQAAAAJ',
                          'aE8woBcAAAAJ',
                          'WTQ2f0QAAAAJ',
                          'NUiEEYkAAAAJ',
                          'pzDPJecAAAAJ',
                          'HdRZK14AAAAJ',
                          'bSWJQIQAAAAJ',
                          '6q5Ft_4AAAAJ',
                          'x8_L6ugAAAAJ',
                          'aCZ8taYAAAAJ',
                          'KjZhyR0AAAAJ',
                          'nkSayMgAAAAJ',
                          'TjbovYgAAAAJ',
                          'Bx4nkngAAAAJ',
                          'bZYjStMAAAAJ',
                          'izqPHwEAAAAJ',
                          'X-z6f5gAAAAJ',
                          '4TIBytYAAAAJ',
                          'OTeSCfEAAAAJ',
                          'Fn2egmsAAAAJ',
                          '1AslBsAAAAAJ',
                          'YVqJ_u8AAAAJ',
                          'cVjuZJoAAAAJ',
                          '21RkigUAAAAJ',
                          'mjueH64AAAAJ',
                          'HOi-BJEAAAAJ',
                          'r2eP6W8AAAAJ',
                          'ieYaJ14AAAAJ',
                          'RbcRyBYAAAAJ',
                          'ELx8lB8AAAAJ',
                          'uGWc5qYAAAAJ',
                          'opcTelwAAAAJ',
                          'ych7DiUAAAAJ',
                          'vUJUSH8AAAAJ',
                          '6FVOh34AAAAJ',
                          'Yi7627oAAAAJ',
                          'a5MoXOYAAAAJ'],
            'email_domain': '@mmmi.sdu.dk',
            'interests': ['Autonomous robots',
                          'artificial intelligence',
                          'swarm intelligence',
                          'complex systems',
                          'evolutionary robotics'],
            'name': 'Anders Lyhne Christensen',
            'organization': 0,
            'scholar_id': 'sKzmsq8AAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=sKzmsq8AAAAJ&citpid=7'},
           {'affiliation': 'Centers for Disease Control',
            'citedby': 16118,
            'citedby5y': 8882,
            'coauthors': [],
            'email_domain': '@cdc.gov',
            'interests': [],
            'name': 'Charles E Rose',
            'organization': 0,
            'scholar_id': 'QBVR0_sAAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=QBVR0_sAAAAJ&citpid=1'},
           {'affiliation': 'LMU Munich',
            'citedby': 2877,
            'citedby5y': 2702,
            'coauthors': [],
            'email_domain': '@econ.lmu.de',
            'interests': ['Behavioral Economics',
                          'Experimental Economics',
                          'Microeconomic Theory',
                          'Meta Science'],
            'name': 'Taisuke Imai',
            'organization': 0,
            'scholar_id': 'jCcimzUAAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=jCcimzUAAAAJ&citpid=5'},
           {'affiliation': 'Professor, McMaster University',
            'citedby': 300389,
            'citedby5y': 142814,
            'coauthors': [],
            'email_domain': '@mcmaster.ca',
            'interests': ['Critical Care Medicine'],
            'name': 'Deborah Cook',
            'organization': 0,
            'scholar_id': 'Iem4ceQAAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=Iem4ceQAAAAJ&citpid=2'},
           {'affiliation': 'Professor of Computer Science and Robotics, '
                           'Università degli Studi di Bergamo',
            'citedby': 2682,
            'citedby5y': 893,
            'coauthors': ['kHhcu94AAAAJ',
                          '1f_iqQwAAAAJ',
                          'Ui4ulbcAAAAJ',
                          'D1c2vPcAAAAJ',
                          'rPCzqN4AAAAJ',
                          'xhUdPh4AAAAJ',
                          'gP-5CSsAAAAJ'],
            'email_domain': '@unibg.it',
            'interests': ['Software Engineering',
                          'Robotics',
                          'Software Architecture',
                          'Control Architecture',
                          'Model driven Engineering'],
            'name': 'Davide Brugali',
            'organization': 0,
            'scholar_id': 'qk4OUXEAAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=qk4OUXEAAAAJ&citpid=2'},
           {'affiliation': 'Professor of Medicine, University of Toronto',
            'citedby': 47195,
            'citedby5y': 28311,
            'coauthors': ['Iem4ceQAAAAJ',
                          'RBbdnj8AAAAJ',
                          'oQcAsYYAAAAJ',
                          'CnQPa4YAAAAJ',
                          'zSeh9ikAAAAJ',
                          'nIgaAGEAAAAJ',
                          'TfFECxMAAAAJ',
                          'JunBXVUAAAAJ'],
            'email_domain': '@utoronto.ca',
            'interests': [],
            'name': 'Sangeeta Mehta MD, FRCPC',
            'organization': 8515235176732148308,
            'scholar_id': 'FtE4rAEAAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=FtE4rAEAAAAJ&citpid=2'},
           {'affiliation': 'IRIDIA, Université Libre de Bruxelles',
            'citedby': 337,
            'citedby5y': 335,
            'coauthors': [],
            'email_domain': '@ulb.ac.be',
            'interests': ['Automatic off-line design',
                          'Swarm robotics',
                          'Artificial Intelligence'],
            'name': 'Antoine Ligot',
            'organization': 0,
            'scholar_id': 'fEAdMGAAAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=fEAdMGAAAAAJ&citpid=1'},
           {'affiliation': 'Full Professor, Dept. Computer Science, Vrije '
                           'Universiteit Amsterdam',
            'citedby': 8094,
            'citedby5y': 3831,
            'coauthors': ['4YAdfEsAAAAJ',
                          'ya3htIoAAAAJ',
                          'u74gQEUAAAAJ',
                          'hwtquZEAAAAJ',
                          'OlYdiYMAAAAJ',
                          'uwshWMoAAAAJ',
                          'PVIyHvUAAAAJ',
                          '5n9E1cMAAAAJ',
                          'pvO-0xwAAAAJ',
                          'l7BGAq8AAAAJ',
                          'h1CRic0AAAAJ',
                          'DmDWmy4AAAAJ',
                          'ngADENUAAAAJ',
                          'xBnjjysAAAAJ',
                          'iQtwztIAAAAJ',
                          'pWVTJ3YAAAAJ',
                          'IPa6m2QAAAAJ',
                          'y494uIgAAAAJ',
                          'cXsfHbsAAAAJ',
                          '2xV8DfcAAAAJ',
                          'yewx0GgAAAAJ',
                          'NUJQv_oAAAAJ',
                          '8hyNFkYAAAAJ',
                          '2AYnxvkAAAAJ',
                          'hH4XfiYAAAAJ',
                          'a2fwDaQAAAAJ',
                          'saLJmksAAAAJ',
                          '0n5S6uUAAAAJ',
                          '1YD0jqAAAAAJ',
                          'MG8iJPAAAAAJ',
                          '7F6-ubIAAAAJ',
                          'K7_ugq8AAAAJ',
                          'pQfY6w4AAAAJ',
                          'shtLH2wAAAAJ',
                          'xul68AwAAAAJ',
                          'V5ILAxAAAAAJ',
                          '3s4lqHkAAAAJ',
                          'VaWnhK4AAAAJ',
                          'FcDxVR8AAAAJ',
                          'NsRgDcUAAAAJ',
                          'WjlaFxcAAAAJ',
                          'xfucOSsAAAAJ',
                          'pazJN8cAAAAJ',
                          '1xtg7VAAAAAJ',
                          'BTaxc1AAAAAJ',
                          '_FfRWVoAAAAJ',
                          'qnyqcEkAAAAJ',
                          'jjCkWXgAAAAJ',
                          'qRnegTsAAAAJ',
                          'jLm9DCkAAAAJ',
                          'iipNiVIAAAAJ',
                          'WZAn2CwAAAAJ',
                          'FWASYv0AAAAJ',
                          'OnRrU-kAAAAJ',
                          'euuV0McAAAAJ',
                          '1I4dbdAAAAAJ',
                          'ZaJzKbwAAAAJ',
                          '4pWyfIQAAAAJ',
                          '4npbuV0AAAAJ',
                          '9LQwMlMAAAAJ',
                          'vwfw0lwAAAAJ',
                          'jlnAa9cAAAAJ',
                          'iQlrBWkAAAAJ',
                          'gm6GQ5UAAAAJ',
                          'BnTgaaIAAAAJ',
                          '-D_BMH4AAAAJ',
                          'aUQ8O9gAAAAJ',
                          'AXYmi1IAAAAJ',
                          'NMuDAe0AAAAJ',
                          '1LViyMgAAAAJ',
                          'fZ3cdbUAAAAJ',
                          'dOeggYMAAAAJ',
                          'cMs97_YAAAAJ',
                          'YUgbZRgAAAAJ',
                          'dpvFqhkAAAAJ',
                          's-gUfQsAAAAJ',
                          '2WLqCEYAAAAJ',
                          'xB1Z6VwAAAAJ',
                          'ntTJhw8AAAAJ',
                          'KHMut54AAAAJ',
                          'SzPo7GIAAAAJ',
                          'r-f9TQEAAAAJ',
                          'NRp_z8EAAAAJ',
                          'K1Akx6sAAAAJ',
                          'Bl4-9VUAAAAJ',
                          'GL_66t0AAAAJ',
                          'i2CPlZQAAAAJ',
                          'gexHei0AAAAJ',
                          'Zy7eB4kAAAAJ',
                          'GfKX3yUAAAAJ',
                          'Wr6oSWIAAAAJ',
                          'xACgrfUAAAAJ',
                          'uB4MBw4AAAAJ',
                          'bBWAQM0AAAAJ',
                          '6Ld7HnYAAAAJ',
                          'Y8BLBGcAAAAJ',
                          'igMJAZwAAAAJ',
                          'lc7YgOcAAAAJ',
                          'hlEYo6wAAAAJ',
                          'qABYFOIAAAAJ',
                          'Q3xxVngAAAAJ',
                          'WhjQewkAAAAJ',
                          'puu5arMAAAAJ',
                          'kR9O4DQAAAAJ',
                          'dqJwPfkAAAAJ',
                          'tpOgD6MAAAAJ',
                          'j6ucyOAAAAAJ',
                          'JdHlU2EAAAAJ',
                          '8HCVx48AAAAJ',
                          'Mcn2e18AAAAJ'],
            'email_domain': '@vu.nl',
            'interests': ['Software Architecture',
                          'Software Engineering',
                          'Software Sustainability',
                          'Energy-aware Software',
                          'Green Software'],
            'name': 'Patricia Lago',
            'organization': 1331960595593680101,
            'scholar_id': 'q5vgzKgAAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=q5vgzKgAAAAJ&citpid=4'},
           {'affiliation': 'Hochschule Bonn-Rhein-Sieg',
            'citedby': 1153,
            'citedby5y': 649,
            'coauthors': ['C2YdbekAAAAJ',
                          '8nWorhwAAAAJ',
                          'T6Hf5e0AAAAJ',
                          'WgxMfwMAAAAJ',
                          'KHhijC0AAAAJ',
                          'NUiEEYkAAAAJ',
                          'xZwripcAAAAJ',
                          '1G9tTMcAAAAJ',
                          'qsOtJtsAAAAJ',
                          'zk5n2Q8AAAAJ',
                          'kHhcu94AAAAJ',
                          'qk4OUXEAAAAJ',
                          't2bSpiMAAAAJ',
                          '_s8-1uAAAAAJ',
                          'flFpWYUAAAAJ'],
            'email_domain': '@h-brs.de',
            'interests': ['Autonomous Systems',
                          'Robotics',
                          'Domain-specific Modeling and Languages',
                          'Trustworthy AI'],
            'name': 'Nico Hochgeschwender',
            'organization': 0,
            'scholar_id': 'GOOxD60AAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=GOOxD60AAAAJ&citpid=2'},
           {'affiliation': 'Associate Professor of Computer Science, '
                           'University of Málaga',
            'citedby': 2794,
            'citedby5y': 1789,
            'coauthors': ['saLJmksAAAAJ',
                          '7F6-ubIAAAAJ',
                          '0icCpp0AAAAJ',
                          'kU5cah4AAAAJ',
                          'gq9hIiAAAAAJ',
                          'NLiNqPwAAAAJ',
                          'UOOb-UkAAAAJ',
                          'x8XlRFgAAAAJ',
                          '35UNdu0AAAAJ',
                          '86H7HmkAAAAJ',
                          'tbVxns0AAAAJ',
                          'DCYQmFYAAAAJ',
                          'MG8iJPAAAAAJ',
                          'l3cF0LoAAAAJ',
                          'Jre2RUQAAAAJ',
                          '_NqFoiYAAAAJ',
                          'Y8BLBGcAAAAJ',
                          'KOC8OykAAAAJ',
                          '1iN71-YAAAAJ',
                          'JsrZG2YAAAAJ',
                          'qrCVP0YAAAAJ',
                          'BQluvIMAAAAJ',
                          'cjgk2esAAAAJ',
                          '--VwkUcAAAAJ',
                          'yiijLskAAAAJ',
                          'o0wtBh0AAAAJ',
                          'DZ5_Gw4AAAAJ',
                          's8F7eWIAAAAJ',
                          '9Mh6OuQAAAAJ',
                          'JXI_gGUAAAAJ',
                          'UmkmLpgAAAAJ',
                          'gXtk7Y0AAAAJ',
                          'tXYPtDgAAAAJ',
                          'tzw-5t0AAAAJ',
                          '3T1ESO8AAAAJ',
                          'mFdINk4AAAAJ',
                          '-xZG2CMAAAAJ',
                          'GGV0yVgAAAAJ',
                          '0nBysEcAAAAJ',
                          'fYIC-BkAAAAJ',
                          'IorrScQAAAAJ',
                          'WNefTDUAAAAJ',
                          'r_SrLZgAAAAJ'],
            'email_domain': '@uma.es',
            'interests': ['Self-Adaptive Systems',
                          'Stochastic Modelling',
                          'Software Architecture',
                          'Verification'],
            'name': 'Javier Cámara',
            'organization': 0,
            'scholar_id': 'iMMncw8AAAAJ',
            'url_picture': 'https://scholar.googleusercontent.com/citations?view_op=view_photo&user=iMMncw8AAAAJ&citpid=5'},
           {'affiliation': 'The Wharton School of the University of '
                           'Pennsylvania',
            'citedby': 1649,
            'citedby5y': 1640,
            'coauthors': [],
            'email_domain': '@upenn.edu',
            'interests': ['psychoneuroendocrinology'],
            'name': 'Dylan Manfredi',
            'organization': 0,
            'scholar_id': 'HgjBXY0AAAAJ',
            'url_picture': ''}]}